title: hoodle 
description: h o o d l e
theme: just-the-docs
color_scheme: dark

url: https://efourd.github.io/hoodle.io

aux_links:
  ♟️: https://github.com/efourd/triplea-howto
  ✉️: http://mail.hoodle.io
